project_id            = "finalfinal-434620"
region                = "us-central1"
zone                  = "us-central1-a"
cluster_name          = "shortlet-autopilot-cluster"
network_name          = "shortlet-network"
subnet_name           = "shortlet-subnetwork"
service_account_email = "oyemprince@gmail.com"
