name: Build and Push to GCR

on:
  push:
    branches:
      - main
    paths:
      - 'api/**'
      - '.github/workflows/**'

  pull_request:
    branches:
      - main
    paths:
      - 'app/**'
      - '.github/workflows/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4


      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2.1.4
        with:
          credentials_json: ${{ secrets.GCR_SA }}
          project_id: ${{ vars.GCP_PROJECT_ID }}

      - name: Configure Docker for Google Container Registry
        run: gcloud auth configure-docker

      - name: Build Docker image
        run: |
          docker build -t gcr.io/${{ vars.GCP_PROJECT_ID }}/${{ vars.IMAGE_NAME }}:latest ./api
          docker push gcr.io/${{ vars.GCP_PROJECT_ID }}/${{ vars.IMAGE_NAME }}:latest
