name: 'Terraform Deployment'

on:
  push:
    branches: [ "main" ]
    paths:
      - 'terraform/**'
      - '.github/workflows/terraform.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'terraform/**'
      - '.github/workflows/terraform.yml'

permissions:
  contents: read

jobs:
  terraform:

    name: 'Terraform Setup'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Google Cloud authentication
        uses: google-github-actions/auth@v2.1.4
        with:
          credentials_json: ${{ secrets.TERRAFORM_SA }}
          project_id: ${{ vars.GCP_PROJECT_ID }}

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Initialize Terraform
        run: terraform init
        working-directory: ./terraform

      - name: Terraform Plan
        run: terraform plan -out=tfplan.binary
        working-directory: ./terraform

      - name: Run Terraform to Apply Resources
        run: terraform apply -auto-approve tfplan.binary
        working-directory: ./terraform
